name: Instituto Trilhas
markdown: kramdown
baseurl: http://caiovitor.com.br/institutotrilhas-teste/
permalink: /institutotrilhas-teste/:year/:month/:day/:title/
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
