name: Instituto Trilhas
markdown: kramdown
baseurl: http://caiovitor.com.br/institutotrilhas-teste/
permalink: date
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
